service: hackmit21
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  whatsapp:
    handler: handler.whatsapp
    events:
      - http:
          path: /
          method: post
          integration: lambda
          response:
            headers:
              Content-Type: "'application/xml'"
            template: $input.path('$')
    environment:
      GOOGLE_KEY: ${ssm:/hackmit21-google-key~true}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
